In [4]:
import numpy as np
import cv2
import pickle
import glob
import json
import pandas as pd

In [5]:
result = pd.read_pickle('calibration.pckl')

In [12]:
print(f'error= {result[0]}\n\n', 
      f'cameraMatrix= \n {result[1]}\n\n', 
      f'distCoeffs= \n {result[2]}\n\n' , 
      f'rvecs= \n {result[3]}\n\n', 
      f'tvec= \n {result[4]}')


error= 0.2948519625749754

 cameraMatrix= 
 [[4.76195023e+03 0.00000000e+00 2.04981141e+03]
 [0.00000000e+00 4.73368492e+03 1.49252250e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

 distCoeffs= 
 [[-3.37366008e+00  8.62028927e+01 -1.34783991e-02  9.54049311e-03
   2.82906419e+02 -3.34581871e+00  8.63952371e+01  2.83448386e+02
  -1.69419034e-02  4.83073609e-03  2.45027336e-02  4.66898399e-03]]

 rvecs= 
 (array([[-0.00346131],
       [ 0.21054051],
       [ 0.01254219]]), array([[-0.08259559],
       [ 0.13351897],
       [ 0.0813843 ]]), array([[-0.0851531 ],
       [ 0.07620913],
       [ 0.00453907]]), array([[-0.0748993 ],
       [ 0.03763162],
       [-0.03151208]]), array([[-0.05074846],
       [ 0.31388354],
       [-0.12596604]]), array([[-0.08983824],
       [ 0.34061628],
       [-0.17152409]]), array([[-0.0084381 ],
       [ 0.29731793],
       [-0.15730816]]), array([[-0.08563373],
       [ 0.1481453 ],
       [-0.13413771]]), array([[-0.07400207],
       [ 0.153628